[package]
name = "trg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
flate2 = "1.1.9"
globset = "0.4.20"
grep-cli = "0.1.12"
grep-matcher = "0.1.9"
grep-printer = "0.3.1"
grep-regex = "0.1.14"
grep-searcher = "0.1.17"
ignore = "0.4.33"
lexopt = "0.3.2"
libc = "0.2.189"
libdeflater = "1.26.0"
num_cpus = "1.17.0"
tar = "0.4.46"
termcolor = "1.4.1"

[dev-dependencies]
assert_cmd = "2.2.2"
tempfile = "3.27.0"

[features]
default = []
zlib-ng = ["flate2/zlib-ng"]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
